default: &default

  api_options:
    # only return section items by default
    f:
      - subcategory|Drill
    # sorting and response number
    sort:
      - date|asc
    num: 50
    # facet info on search page
    facet_limit: 20
    facet_sort: count|desc
    # facet info on browse page
    browse_sort: term|asc
    # highlighting
    hl_num: 5

  facets:
    en:
      date.year:
        label: Year
        flags:
          - search_filter
      person.name:
        label: People
        flags:
          - search_filter
      keywords:
        label: Topics
        flags:
          - search_filter
      publisher:
        label: Periodical
        flags:
          - search_filter
# Add fields for other languages with their language code
#    es:
#      category:
#        label: Categoría
#        flags:
#          - search_filter
#          - translate

test:
  <<: *default

development:
  <<: *default

production:
  <<: *default
