default: &default
  # If app should only be using a specific collection,
  # append "/collection/(collection_name)" to path
  api_path: https://servername.unl.edu/api/v2/collection/bandhistory
  # path to iiif server, NOT including the project directory
  iiif_path: https://cdrhmedia.unl.edu/iiif/2

test:
  <<: *default

development:
  <<: *default
  api_path: https://servername.unl.edu/api/v2/collection/bandhistory
  iiif_path: https://cdrhmedia.unl.edu/iiif/2
  media_path: https://servername.unl.edu/media

production:
  <<: *default
  api_path: https://servername.unl.edu/api/v2/collection/bandhistory
  iiif_path: https://cdrhmedia.unl.edu/iiif/2
  media_path: https://servername.unl.edu/media
