#############
## STORIES ##
#############

-
  method:     r301
  from:       /stories/lentz-interview
  to:         /stories/accounts/lentz

-
  method:     r301
  from:       /stories/johnson-interview
  to:         /stories/accounts/johnson

-
  method:     r301
  from:       /stories/steffens
  to:         /stories/accounts/steffens

-
  method:     r301
  from:       /stories/marches
  to:         /stories/features/marches


############
## IMAGES ##
############

-
  # mb016 ->  band.img.0016
  method:     r301
  from:       !ruby/regexp /^\/multimedia\/images\/mb0(\d{2})\/$/
  to:         /multimedia/images/band.img.00$1

-
  method:     r301
  from:       /multimedia/images/js001
  to:         /multimedia/images/band.img.0020

-
  # ab001 ->  band.img.0021
  method:     r301
  from:       !ruby/regexp /^\/multimedia\/images\/ab00(\d)\/$/
  to:         /multimedia/images/band.img.002$1

-
  # rg150833 -> rg570903 snider rg change
  method:     r301
  from:       !ruby/regexp /^\/multimedia\/images\/150833-(\d{5})$/
  to:         /multimedia/images/570903-$1

-
  # rg150813 -> rg570904 lentz / steffens rg change
  method:     r301
  from:       !ruby/regexp /^\/multimedia\/images\/150813-(\d{5})$/
  to:         /multimedia/images/570904-$1


###########
# FOOTAGE #
###########

-
  # 4.01.01 -> 1.02.01
  method:     r301
  from:       !ruby/regexp /^\/multimedia\/footage\/4\.\d{2}\.(\d{2})$/
  to:         /multimedia/footage/1.02.$1

-
  # 5.01.01 -> 1.03.01
  method:     r301
  from:       !ruby/regexp /^\/multimedia\/footage\/5\.\d{2}\.(\d{2})$/
  to:         /multimedia/footage/1.03.$1
